CHERRYUSB_BASE:=3rdpart/cherryusb

CHERRYUSB_INC:=$(CHERRYUSB_BASE)/common
CHERRYUSB_INC+=$(CHERRYUSB_BASE)/core
CHERRYUSB_INC+=$(CHERRYUSB_BASE)/osal
CHERRYUSB_INC+=$(CHERRYUSB_BASE)/class/cdc
CHERRYUSB_INC+=$(CHERRYUSB_BASE)/class/hid
CHERRYUSB_INC+=$(CHERRYUSB_BASE)/class/msc
CHERRYUSB_INC+=$(CHERRYUSB_BASE)/class/audio
CHERRYUSB_INC+=$(CHERRYUSB_BASE)/class/video
CHERRYUSB_INC+=$(CHERRYUSB_BASE)/class/hub
CHERRYUSB_INC+=$(CHERRYUSB_BASE)/class/wireless
CHERRYUSB_INC+=$(CHERRYUSB_BASE)/port/ch32

CHERRYUSB_SRC:=$(CHERRYUSB_BASE)/core/usbd_core.c
ifeq ($(strip $(CHERRYUSB_CLASS)),)
CHERRYUSB_SRC+=$(wildcard $(CHERRYUSB_BASE)/class/*/usbd_*.c)
else
CHERRYUSB_SRC+=$(CHERRYUSB_BASE)/class/$(CHERRYUSB_CLASS)/usbd_$(CHERRYUSB_CLASS).c
endif
CHERRYUSB_SRC+=$(CHERRYUSB_BASE)/port/ch32/usb_dc_usb$(CHERRYUSB_DEV).c
CHERRYUSB_DEF:=

DEFINES+=$(CHERRYUSB_DEF)
INCLUDES+=$(CHERRYUSB_INC)
C_SRC+=$(CHERRYUSB_SRC)
